#!/usr/bin/env python3
"""Create a SemanticKITTI layout compatible with OccAny's KittiDataset.

The adapter directory is made from symlinks, so large image/lidar/voxel files
are not copied. It is safe to delete and recreate.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


MARKER = ".occany_semantickitti_adapter"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build an OccAny-compatible SemanticKITTI dataset adapter."
    )
    parser.add_argument(
        "--semantickitti-root",
        type=Path,
        default=Path("/home/dataset-local/lr/data/semantickitti"),
        help="Root containing sequences/ with images, velodyne, and voxels.",
    )
    parser.add_argument(
        "--kitti-semantic-root",
        type=Path,
        default=Path("/home/dataset-local/lr/data/kitti_semantic"),
        help="Root containing per-sequence calib.txt with Tr, poses.txt, and labels/.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path("/home/dataset-local/lr/data/semantickitti_occany_root"),
        help="Adapter root to pass as DSDIR. The script creates dataset/sequences under it.",
    )
    parser.add_argument(
        "--sequences",
        nargs="*",
        help="Optional sequence ids to align, e.g. 08 09 10. Defaults to all shared sequences.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Remove and recreate output-root if it was previously generated by this script.",
    )
    return parser.parse_args()


def ensure_has_tr(calib_path: Path) -> None:
    with calib_path.open("r", encoding="utf-8") as f:
        if not any(line.startswith("Tr:") for line in f):
            raise RuntimeError(f"{calib_path} does not contain a Tr: calibration row")


def symlink(src: Path, dst: Path) -> None:
    if not src.exists():
        raise FileNotFoundError(src)
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    dst.symlink_to(src)


def prepare_output(output_root: Path, force: bool) -> Path:
    dataset_root = output_root / "dataset"
    marker_path = output_root / MARKER

    if output_root.exists():
        if not marker_path.exists():
            raise RuntimeError(
                f"{output_root} already exists and was not created by this script. "
                "Choose a different --output-root."
            )
        if not force:
            raise RuntimeError(
                f"{output_root} already exists. Re-run with --force to recreate it."
            )
        shutil.rmtree(output_root)

    (dataset_root / "sequences").mkdir(parents=True)
    marker_path.write_text("generated by tools/align_semantickitti_for_occany.py\n", encoding="utf-8")
    return dataset_root


def sequence_errors(sequence: str, sem_root: Path, kitti_semantic_root: Path) -> list[str]:
    sem_seq = sem_root / "sequences" / sequence
    kitti_seq = kitti_semantic_root / sequence
    checks = [
        sem_seq / "image_0",
        sem_seq / "image_1",
        sem_seq / "image_2",
        sem_seq / "image_3",
        sem_seq / "velodyne",
        sem_seq / "voxels",
        kitti_seq / "calib.txt",
        kitti_seq / "poses.txt",
        kitti_seq / "labels",
    ]

    errors = [f"missing {path}" for path in checks if not path.exists()]
    if (kitti_seq / "calib.txt").exists():
        try:
            ensure_has_tr(kitti_seq / "calib.txt")
        except RuntimeError as exc:
            errors.append(str(exc))
    return errors


def complete_sequences(sem_root: Path, kitti_semantic_root: Path) -> tuple[list[str], dict[str, list[str]]]:
    sem_sequences = {p.name for p in (sem_root / "sequences").iterdir() if p.is_dir()}
    kitti_sequences = {p.name for p in kitti_semantic_root.iterdir() if p.is_dir()}
    candidates = sorted(sem_sequences & kitti_sequences)

    selected = []
    skipped = {}
    for sequence in candidates:
        errors = sequence_errors(sequence, sem_root, kitti_semantic_root)
        if errors:
            skipped[sequence] = errors
        else:
            selected.append(sequence)
    return selected, skipped


def align_sequence(sequence: str, sem_root: Path, kitti_semantic_root: Path, dataset_root: Path) -> None:
    sem_seq = sem_root / "sequences" / sequence
    kitti_seq = kitti_semantic_root / sequence
    out_seq = dataset_root / "sequences" / sequence
    out_seq.mkdir(parents=True)

    calib_path = kitti_seq / "calib.txt"
    ensure_has_tr(calib_path)

    symlink(calib_path, out_seq / "calib.txt")
    symlink(kitti_seq / "poses.txt", out_seq / "poses.txt")
    symlink(kitti_seq / "labels", out_seq / "labels")

    for name in ("image_0", "image_1", "image_2", "image_3", "velodyne", "voxels"):
        symlink(sem_seq / name, out_seq / name)

    times_path = sem_seq / "times.txt"
    if times_path.exists():
        symlink(times_path, out_seq / "times.txt")


def main() -> None:
    args = parse_args()
    sem_root = args.semantickitti_root.resolve()
    kitti_semantic_root = args.kitti_semantic_root.resolve()
    output_root = args.output_root.resolve()

    skipped = {}
    if args.sequences:
        sequences = sorted(args.sequences)
    else:
        sequences, skipped = complete_sequences(sem_root, kitti_semantic_root)

    if not sequences:
        raise RuntimeError("No sequences selected or found in both source roots.")

    dataset_root = prepare_output(output_root, args.force)
    for sequence in sequences:
        errors = sequence_errors(sequence, sem_root, kitti_semantic_root)
        if errors:
            details = "\n  ".join(errors)
            raise RuntimeError(f"Sequence {sequence} is incomplete:\n  {details}")
        align_sequence(sequence, sem_root, kitti_semantic_root, dataset_root)

    print(f"Aligned {len(sequences)} sequences into: {output_root}")
    if skipped:
        skipped_ids = ", ".join(skipped)
        print(f"Skipped incomplete sequences: {skipped_ids}")
    print("Use it with:")
    print(f"  export DSDIR={output_root}")


if __name__ == "__main__":
    main()
